//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_APP_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WC_Inbox
    {
        public long ID { get; set; }
        public int EmployeeID { get; set; }
        public int Org_Number { get; set; }
        public System.DateTime Hire_Date { get; set; }
        public string Job_Title { get; set; }
        public int Work_Schedule { get; set; }
        public System.DateTime Injury_Date { get; set; }
        public string Injury_Time { get; set; }
        public bool DOT_12 { get; set; }
        public string Start_Time { get; set; }
        public string Injured_Body_Part { get; set; }
        public string Side { get; set; }
        public bool Missing_Work { get; set; }
        public Nullable<System.DateTime> Return_to_Work_Date { get; set; }
        public Nullable<bool> Doctors_Release { get; set; }
        public Nullable<bool> Treatment { get; set; }
        public string Injury_Description { get; set; }
        public string Equipment { get; set; }
        public string Witness { get; set; }
        public string Questioned { get; set; }
        public string Medical_History { get; set; }
        public bool Inbox_Submitted { get; set; }
        public string Comments { get; set; }
        public string User_Email { get; set; }
        public string Contact_Email { get; set; }
        public string Specialist_Email { get; set; }
        public string Optional_Email { get; set; }
        public string Optional_Email2 { get; set; }
        public string Optional_Email3 { get; set; }
        public string Optional_Email4 { get; set; }
        public string Add_User { get; set; }
        public System.DateTime Date_Added { get; set; }
        public string InboxID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
