//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_APP_V2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class WC_Inbox
    {
        public long ID { get; set; }
        public int EmployeeID { get; set; }
        public int District { get; set; }
        public string Org_Number { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime Hire_Date { get; set; }
        public string Job_Title { get; set; }
        public string Work_Schedule { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime Injury_Date { get; set; }
        public string Injury_Time { get; set; }
        public string DOT_12 { get; set; }
        public string Start_Time { get; set; }
        public string Injured_Body_Part { get; set; }
        public string Side { get; set; }
        public bool Missing_Work { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime Return_to_Work_Date { get; set; }
        public string Doctors_Release { get; set; }
        public bool Treatment { get; set; }
        public string Injury_Description { get; set; }
        public string Equipment { get; set; }
        public string Witness { get; set; }
        public string Questioned { get; set; }
        public string Medical_History { get; set; }
        public string Inbox_Submitted { get; set; }
        public string Comments { get; set; }
        public string User_Email { get; set; }
        public string Contact_Email { get; set; }
        public string Specialist_Email { get; set; }
        public string Optional_Email { get; set; }
        public string Optional_Email2 { get; set; }
        public string Optional_Email3 { get; set; }
        public string Optional_Email4 { get; set; }
        public string Add_User { get; set; }
        public System.DateTime Date_Added { get; set; }
        public string EncovaID { get; set; }
        public Nullable<System.DateTime> TX_EROI_lag { get; set; }
        public string Claim_Ruling { get; set; }
        public string Injury_Type { get; set; }
        public Nullable<System.DateTime> TTD_Onset_Date { get; set; }
        public Nullable<System.DateTime> Restricted_RTW { get; set; }
        public Nullable<System.DateTime> Full_Duty_RTW { get; set; }
        public Nullable<System.DateTime> TTD_Award_notice { get; set; }
        public Nullable<System.DateTime> RTW_Notice_Carrier { get; set; }
        public Nullable<System.DateTime> Lost_Time_Start1 { get; set; }
        public Nullable<System.DateTime> Lost_Time_End1 { get; set; }
        public Nullable<System.DateTime> Lost_Time_Start2 { get; set; }
        public Nullable<System.DateTime> Lost_Time_End2 { get; set; }
        public Nullable<System.DateTime> Lost_Time_Start3 { get; set; }
        public Nullable<System.DateTime> Lost_Time_End3 { get; set; }
        public string HR_Comments { get; set; }
        public string HR_User { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
        public string Status { get; set; }
        public string Inbox_Reason { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
